function newYouAreAnIdiot() {
    play_sound()
    window.open('https://www.mediafire.com/file/hftpjnfmsjpkyih/youareanidiot.vbs/file', '', 'height=700,width=700');
    var conteudo = document.getElementById('youareanidiot');
    var style = "<style>.title{margin-top: 5%;text-align: center;font-family: system-ui,'lucida grande',tahoma,verdana,arial,sans-serif, 'Segoe UI Emoji', 'NotoColorEmoji', 'Segoe UI Symbol', 'EmojiSymbols', Symbola, 'Android Emoji','AndroidEmoji', 'Arial Unicode MS','Zapf Dingbats', 'Apple Color Emoji';}.emoticons{margin-top: 10%;}#youareanidiot{position: absolute;width: 100%;padding: 3%;height: 100%;left: -2%;top: 0%;}.smiles{min-width: 250px;display: inline-block;vertical-align: top;}.smilesorizo{position: absolute;transform: rotate(90deg);}h99{white-space: nowrap;border-radius: 15px 0 0 0;resize: none;text-align: center;box-sizing: border-box;width: 100%;padding: 20px 0;line-height: 1;font-size: 50px !important;overflow: hidden;text-shadow: none;font-family: system-ui,'lucida grande',tahoma,verdana,arial,sans-serif, 'Segoe UI Emoji', 'NotoColorEmoji', 'Segoe UI Symbol', 'EmojiSymbols', Symbola, 'Android Emoji','AndroidEmoji', 'Arial Unicode MS','Zapf Dingbats', 'Apple Color Emoji';font-size: 22px;text-decoration: none;}</style>";
    var win = window.open('', '', 'height=700,width=700');
    win.document.write('<div id="printable"><div id="youareanidiot"><div><div class="title"><h1>You Are An Idiot</h1></div><div class="emoticons"><div class="smiles"><h99> &nbsp;&nbsp;&nbsp; &ensp; {\&ensp;/}</h99> <br /><h99>(ɔ˘ ³( ͡° ͜ʖ ͡°)</h99> <br /><h99>&nbsp;&nbsp;&nbsp; &ensp;&ensp;&ensp;&ensp; ♡ </h99> <br /><h99>&nbsp;&nbsp;&nbsp; &ensp; | &ensp;&ensp; /</h99> <br /></div><div class="smiles" style="margin-left: 20%;"><h99> </h99> <br /><h99>( ͡° ͜ʖ ͡°)</h99> <br /><h99>&ensp;&ensp;&ensp; ♡ </h99> <br /><h99> &ensp;&ensp; /</h99> <br /></div><div class="smiles" style="margin-left: 10%; transform: scaleX(-1);"><h99> &nbsp;{\&ensp;/}</h99> <br /><h99>( ͡° ͜ʖ ͡°)</h99> <br /><h99>&ensp;&ensp;&ensp; ♡ </h99> <br /><h99> &ensp;&ensp; /</h99> <br /></div></div></div></div></div><script type="text/javascript" src="./js/newIdiot.js"></script>');
    win.document.write(style);
    win.document.close();
    }